title: Claucookie Labs
logo: /assets/img/logo.png
description: Software Development made with Love
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
